spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yangyuguang-kerl/config.git
          username: yangyuguang-kerl
          password: yang199626
      label: master
  application:
    name: config
management:
  endpoint:
    shutdown:
      enabled: false
server:
  port: 9090