rocketmq:
  name-server: 192.168.1.201:9876;192.168.1.111:9876;192.168.1.101:9876 #rocketmq服务地址
  producer:
    group: rocketmq_test #自定义的组名称
    send-message-timeout: 3000  #消息发送超时时长
server:
  port: 9091