spring:
  application:
    name: register-consumer-no-api
dubbo:
  application:
    name: register-consumer
  registry:
    address: nacos://127.0.0.1:8848
    check: false
    parameters:
      namespace: b21c6bb1-be4b-4f99-a0b7-ea2619318fa9
#  provider:
#    serialization: kryo
server:
  port: 8082