spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kerlier/fashion-cloud-config.git
          username: kerlier
          password: yang199626
      label: dev
  application:
    name: config
server:
  port: 9090